part2.plant_perts:
  type: product
  of:
    - type: config
      name: noise_levels
      of:
        train:
          model:
            feedback_noise_std: [0.01, 0.1]
            motor_noise_std:    [0.01, 0.1]
        model:
          feedback_noise_std: [0.01, 0.1]
          motor_noise_std:    [0.01, 0.1]

    - type: config
      name: delays
      of:
        train.model.feedback_delay_steps: [0, 5]

    - type: cases
      name: disturbance_types
      of:
        - type: config
          name: curl
          of:
            train:
              pert:
                type: curl
                std: !Literal [0.0, 0.5, 1.0, 1.5]
            pert:
              type: curl
              amp: !Literal [0.0, 4.0]

        - type: config
          name: constant
          of:
            train:
              pert:
                type: constant
                std: !Literal [0, 0.01, 0.1, 1]
            pert:
              type: constant
              std: !Literal [0, 0.4]

# part1.plant_perts: null