
# If `base == ""`, then the remaining keys are interpreted as absolute paths,
# or as relative to this YAML file
base: /tmp/rlrmp

db: db
models: models
figures: figures
figures_dump: figures_dump
cache: cache
logs: logs