#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
train:
  pert:  
    type: curl
    # list -> load multiple models
    std: [0.0, 0.5, 1.0, 1.5]  

sisu: [-3., -2., -1., 0., 1., 2., 3.]

eval_n: 10
  
task:  # Passed to the base task constructor
  full:
    eval_grid_n: 2
    eval_n_directions: 24
    # eval_reach_length: 0.5
  small:
    eval_grid_n: 1
    eval_n_directions: 7
    # eval_reach_length: 0.5

pert:
  # null -> same as during training, e.g. load.train.pert.type in this case
  type: null 
  amp: [0.0, 4.0] 
  # constant -> [0.0, 0.4],

model:
  n_steps: 150
  feedback_noise_std: null
  motor_noise_std: null

analyses:
  center_out_sets: 
    i_replicate: null
