#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
train:
  pert:  
    type: curl
    std: [0.0, 0.5] 

eval_n: 50
  
task:  # Passed to the base task constructor
  full:
    eval_grid_n: 10
    eval_n_directions: 1
    eval_reach_length: 0

pert:
  # null -> same as during training, e.g. load.train.pert.type in this case
  type: null 
  amp: [0, 0.5, 1.0, 2.0, 4.0] 

model:
  n_steps: 200
  feedback_noise_std: 0.1
  motor_noise_std: 0.1
  dt: 0.05  #! Remove
  
  
  