train:
  model:  
    n_replicates: 5
    n_steps: 100  
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
    damping: 10
    tau_rise: 0.05
  # where: 
  #   0: ['step.net.hidden', 'step.net.readout']
  # intervention_scaleup_batches=[0,0],
  # state_reset_iterations=[],
  # readout_norm_loss_weight: 0.0
  # readout_norm_value: 2.0
  
eval_n: 10

model:
  n_steps: null
  feedback_noise_std: null
  motor_noise_std: null
